version: "3.9"
networks:
  backend:
    driver: bridge
services: 
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Slicecake-backend/Dockerfile
    ports:
      - 5000:80
    networks:
      - backend
    depends_on: 
      - postgres_db
  postgres_db:
    container_name: postgre
    image: postgres:latest
    environment:
      POSTGRES_DB: sc_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: terrarik22
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: